COPY 	START 	1000	.COPY FILE FROM INPUT TO OUTPUT
.FIRST	STL	READADR	.SAVE RETURN ADDRESS
CLOOP	JSUB	RDREC	.READ INPUT RECORD
	LDA	LENGTH	.TEST FOR EOF(LENGTH = 0)
	COMP	ZERO	
	JEQ	ENDFIL	.EXIT IF EOF FOUND
	JSUB	WRREC	.WRITE OUTPUT RECORD
	J	CLOOP	.LOOP
ENDFIL	LDA	EOF	.INSERT END OF FILE MARKER
	STA	BUFFER	
	LDA	THREE	.SET LENGTH = 3
	STA	LENGTH	
	JSUB	WRREC	.WRITE EOF
.	LDL	RETADR	.GET RETURN ADDRESS
.	RSUB		.RETURN TO CALLER
A	J	A
EOF	BYTE	C'EOF'
THREE	WORD	3
ZERO	WORD	0
END	WORD	1
ASEN	WORD	10	.ASCII CODE OF 'ENTER'
RETADR	RESW	1	
LENGTH	RESW	1	.LENGTH OF RECORD
BUFFER	RESB	4096	.4096-BYTE BUFFER AREA

RDREC	LDX	ZERO	.CLEAR LOOP COUNTER
	LDA	ZERO	.CLEAR A TO ZERO
RLOOP	TD	INPUT	.TEST INPUT DEVICE
	JEQ	RLOOP	.LOOP UNTIL READY
	RD	INPUT	.READ CHARACTER INTO REGISTER A -> BUFFER
	COMP	ASEN	.TEST FOR END OF RECORD
	JEQ	EXIT	.EXIT LOOP IF EOR
	STCH	BUFFER,X.STORE CHARACTER IN BUFFER
	TIX	MAXLEN	.LOOP UNLESS MAX LENGTH
	JLT	RLOOP	.HAS BEEN REACHED
EXIT	STX	LENGTH	.SAVE RECORD LENGTH
	RSUB
INPUT	BYTE 	0	.CODE FOR INPUT DEVICE
MAXLEN	WORD	4096

WRREC	LDX	ZERO
WLOOP	TD	OUTPUT	.CLEAR LOOP COUNTER
	JEQ	WLOOP	.LOOP UNTIL READY
	LDCH	BUFFER,X.GET CHARACTER FROM BUFFER
	WD	OUTPUT	.WRITE CHARACTER
	TIX	LENGTH	.LOOP UNTILL ALL CHARACTERS
	JLT	WLOOP	.HAVE BEEN WRITTEN
	RSUB		.RETURN TO CALLER
OUTPUT	BYTE	1	.CODE FOR OUTPUT DEVICE
	END	COPY
