	LDA	ALPHA	.LOAD ALPHA INTO REGISTER A
	ADD	INCR	.ADD THE VALUE OF INCR
	SUB	ONE	.SUBRTRACT 1
	STA	BETA	.STORE IN BETA
	LDA	GAMMA	.LOAD GAMMA INTO REGISTER A
	ADD	INCR	.ADD THE VALUE OF INCRR
	SUB	ONE	.SUBTRACT 1
	STA	DELTA	.STORE IN DELTA

ONE	WORD	1
ALPHA	WORD	7
BETA	RESW	1
GAMMA	WORD	3
DELTA	RESW	1
INCR	RESW	1	
