	LDS	INCR	.LOAD VALUE OF INCR INTO REGISTER S
	LDA	ALPHA	.LOAD ALPHA INTO REGISTER A
	ADDR	S,A	.ADD THE VALUE OF INCR
	SUB	#1	.SUBRTRACT 1
	STA	BETA	.STORE IN BETA
	LDA	GAMMA	.LOAD GAMMA INTO REGISTER A
	ADDR	S,A	.ADD THE VALUE OF INCR
	SUB	#4	.SUBTRACT 4
	STA	DELTA	.STOR IN DELTA

ONE 	WORD	1
ALPHA	WORD	7
BETA	RESW	1
GAMMA	WORD	3
DELTA	RESW	1
INCR	WORD	4
