COPY	START	0
	LDA	#5	.LOAD IMEDIATE VALUE 5 INT REGISTER A
	STA	ALPHA	.STORE IN ALPHA	
	LDA	#90	.LOAD ASCII CODE FOR 'Z' INTO REGISTER A
	STCH	C1	.STORE IN CHARACTER VARIABLE C1

ALPHA	RESW	1	.ONE-WORD VARIABLE
C1	RESB	1	.ONE-BYTE VARIABLE	