INLOOP	TD	INDEV	.TEST INPUT DEVICE
	JEQ	INLOOP	.LOOP UNTILL DEVICE IS READY
	RD	INDEV	.READ ONE BYTE FROM INPUT DEVICE INTO REGISTER A
	STA	DATA	.STORE BYTE THAT WAS READ

OUTLP	TD	OUTDEV	.TEST OUTPUT DEVICE
	JEQ	OUTLP	.LOOP INTILL DEVICE IS READY
	LDA	DATA	.LOAD DATA BYTE INTO REGISTER A
	WD	OUTDEV	.WRITE ONE BYTE TO OUTPUT DEVICE

INDEV	BYTE	0	.INPUT DEVICE NUMBER
OUTDEV	BYTE	1	.OUTPUT DEVICE NUMBER
DATA	RESB	1	.ONE-BYTE VARIABLES